version: '3'

networks:
    bibbox-default-network:
      external: true

services:
  # base app
  openspecimen-fdp-web:
    image: bibbox/openspecimen:v8-2-RC2
    container_name: openspecimen-fdp-web
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - openspecimen-fdp-db:openspecimen-db
    environment:
      - DATABASE_HOST=openspecimen-db
      - MYSQL_ROOT_PASSWORD=openspecimen
      - MYSQL_DATABASE=openspecimen
      - MYSQL_USER=openspecimen
      - MYSQL_PASSWORD=openspecimen
    depends_on:
      - openspecimen-fdp-db
    volumes:
      - ./data/os-data:/var/lib/openspecimen/data
      - ./data/os-plugins:/var/lib/openspecimen/plugins
      - ./images/openspecimen/configs/openspecimen/ROOT:/var/lib/tomcat9/webapps/ROOT
      - ./images/openspecimen/configs/openspecimen/scripts/entrypoint.sh:/opt/scripts/entrypoint.sh
    ports:
      - "9000:8080"

  openspecimen-fdp-db:
    image: mysql:8.0.26
    container_name: openspecimen-fdp-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    environment:
      - MYSQL_ROOT_PASSWORD=openspecimen
      - MYSQL_DATABASE=openspecimen
      - MYSQL_USER=openspecimen
      - MYSQL_PASSWORD=openspecimen
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./images/openspecimen/configs/openspecimen.cnf:/etc/mysql/conf.d/openspecimen.cnf:ro #read only
    cap_add:
      - SYS_NICE 
  # fdp containers
  jupyter-openspecimen-fdp:
    image: jupyter/datascience-notebook
    container_name:  openspecimen-fdp-jupyter
    restart: unless-stopped
    networks:
      - bibbox-default-network
    ports:
        - "8888:8888"
    volumes:
        - ./home/jovyan/work:/home/jovyan/work

  fdp:
    image: "nlesc/fairdatapoint"
    container_name:  openspecimen-fdp-fdp
    restart: unless-stopped
    depends_on:
      - virtuoso
    environment:
      - FDP_HOST=0.0.0.0
      - FDP_PORT=8888
    networks:
      - bibbox-default-network
    ports:
      - "8080:8888"
    

  fdpsearch:
    image: "nlesc/fairdatapoint-search"
    container_name:  openspecimen-fdp-fdpsearch
    restart: unless-stopped
    ports:
      - "8088:8088"
    environment:
      - GRLC_SPARQL_ENDPOINT=http://virtuoso:8890/sparql
      - DEBUG=false
    depends_on:
      - virtuoso
    networks:
      - bibbox-default-network

  virtuoso:
    image: "nlesc/virtuoso"
    container_name:  openspecimen-fdp-virtuoso
    restart: unless-stopped
    environment:
      - SPARQL_UPDATE=true
    volumes:
      - ./data/virtuoso:/data   
    networks:
      - bibbox-default-network

