version: '3'

networks:
    bibbox-default-network:
      external: true

services:
  # base app
  openspecimen-fdp-web:
    image: bibbox/openspecimen:9-0-RC2
    container_name: openspecimen-fdp-web
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - openspecimen-fdp-db:openspecimen-db
    environment:
      - DATABASE_HOST=openspecimen-db
      - MYSQL_ROOT_PASSWORD=openspecimen
      - MYSQL_DATABASE=openspecimen
      - MYSQL_USER=openspecimen
      - MYSQL_PASSWORD=openspecimen
    depends_on:
      - openspecimen-fdp-db
    volumes:
      - ./data/os-data:/var/lib/openspecimen/data
      - ./data/os-plugins:/var/lib/openspecimen/plugins
      - ./images/openspecimen/configs/openspecimen/ROOT:/var/lib/tomcat9/webapps/ROOT
      - ./images/openspecimen/configs/openspecimen/scripts/entrypoint.sh:/opt/scripts/entrypoint.sh
    ports:
      - "9000:8080"

  openspecimen-fdp-db:
    image: mysql:8.0.26
    container_name: openspecimen-fdp-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    environment:
      - MYSQL_ROOT_PASSWORD=openspecimen
      - MYSQL_DATABASE=openspecimen
      - MYSQL_USER=openspecimen
      - MYSQL_PASSWORD=openspecimen
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./images/openspecimen/configs/openspecimen.cnf:/etc/mysql/conf.d/openspecimen.cnf:ro #read only
    cap_add:
      - SYS_NICE 
  # fdp containers
  jupyter-openspecimen-fdp:
    image: jupyter/datascience-notebook:notebook-6.4.11
    container_name:  openspecimen-fdp-jupyter
    restart: unless-stopped
    links:
      - openspecimen-fdp-web:openspecimen
      - fdp-client:fdp-client
      - openspecimen-pap-neo4j:pap-neo4j

    networks:
      - bibbox-default-network
    environment:
      - JUPYTER_TOKEN=FDP
    ports:
        - "8888:8888"
    volumes:
        - ./data/jupyter/home/jovyan/work:/home/jovyan/work

  fdp:
    image: fairdata/fairdatapoint:1.13.1
    container_name:  openspecimen-fdp-fdp
    restart: unless-stopped
    networks:
      - bibbox-default-network
    ports:
      - "8080:80"
    volumes:
      - ./data/application.yml:/fdp/application.yml:ro
    links:
      - blazegraph:blazegraph
      - mongo:mongo
    environment:
      - CLIENTURL=http://localhost:8088

  fdp-client:
    image: fairdata/fairdatapoint-client:1.13.0
    container_name:  openspecimen-fdp-fdp-client
    restart: unless-stopped
    ports:
      - 8088:80
    environment:
      - FDP_HOST=fdp
    links:
      - fdp:fdp
    networks:
      - bibbox-default-network

  mongo:
    image: mongo:4.0.12
    container_name:  openspecimen-fdp-mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo/data:/data/db
    networks:
      - bibbox-default-network

  blazegraph:
    image: metaphacts/blazegraph-basic:2.2.0-20160908.003514-6
    container_name:  openspecimen-fdp-blazegraph
    restart: unless-stopped
    ports:
      - 8081:8080
    volumes:
      - ./data/blazegraph:/blazegraph-data
    networks:
      - bibbox-default-network

  openspecimen-pap-neo4j:
    image: neo4j:3.5
    container_name: openspecimen-pap-neo4j
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - bibbox-default-network
    volumes:
      - ./data/neo4j/conf:/conf
      - ./data/neo4j/data:/data
      - ./data/neo4j/import:/import
      - ./data/neo4j/logs:/logs
      - ./data/neo4j/plugins:/plugins
    environment: 
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G

