version: '3'

networks:
    bibbox-default-network:
      external: true

services:
  # base app
  openspecimen-web:
    image: bibbox/openspecimen:v8-0-x
    container_name: openspecimen-web
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - openspecimen-db:openspecimen-db
    environment:
      - DATABASE_HOST=openspecimen-db
      - MYSQL_ROOT_PASSWORD=openspecimen
      - MYSQL_DATABASE=openspecimen
      - MYSQL_USER=openspecimen
      - MYSQL_PASSWORD=openspecimen
      - TOMCAT_MANAGER_USER=openspecimen
      - TOMCAT_MANAGER_PASSWORD=openspecimen
      - INSTITUTE_NAME=BIBBOX Demo Biobank
      - EMAIL_ADRESS="admin@bibbox.org"
      - FIRST_NAME=admin
      - LAST_NAME=Bibbox
      - LOGIN_NAME=bibboxadmin  
    depends_on:
      - openspecimen-db
    volumes:
      - ./data/os-data:/var/lib/openspecimen/data
      - ./data/os-plugins:/var/lib/openspecimen/plugins
    ports:
      - "9000:8080"

  openspecimen-db:
    image: mysql:8.0
    container_name: openspecimen-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    environment:
      - MYSQL_ROOT_PASSWORD=openspecimen
      - MYSQL_DATABASE=openspecimen
      - MYSQL_USER=openspecimen
      - MYSQL_PASSWORD=openspecimen
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./images/openspecimen/configs/openspecimen.cnf:/etc/mysql/conf.d/openspecimen.cnf #read only

  # fdp containers
  jupyter:
    image: jupyter/datascience-notebook
    container_name:  jupyter
    restart: unless-stopped
    networks:
      - bibbox-default-network
    ports:
        - "8888:8888"
    volumes:
        - ./home/jovyan/work:/home/jovyan/work

  fdp:
    image: "nlesc/fairdatapoint"
    restart: unless-stopped
    depends_on:
      - virtuoso
    environment:
      - FDP_HOST: "0.0.0.0"
      - FDP_PORT: "8888"

  fdpsearch:
    image: "nlesc/fairdatapoint-search"
    restart: unless-stopped
    ports:
      - "8088:8088"
    environment:
      - GRLC_SPARQL_ENDPOINT=http://virtuoso:8890/sparql
      - DEBUG=false
    depends_on:
      - virtuoso

  virtuoso:
    image: "nlesc/virtuoso"
    restart: unless-stopped
    environment:
      - SPARQL_UPDATE=true
    volumes:
      - ./data/virtuoso:/data
